### ISSUE TITLE
Need more explanations

### ISSUE THREAD

**Issue by neozhaoliang** [Syntopia/Polytopia#1]
Hi Syntopia: thanks for this nice project and the detailed images! I think I can understand almost all the math stuff here except one: in the section "generate geometry from group structure" you said

> We also need to figure out a starting point: gram-schmidt: take the ordered set of normals and create an orthogonal representation. 

What do you mean by "orthogonal representation" here?  I guess you want to find three vectors `v1, v2, v3` so that the normal of the plane spanned by `v1, v2` is `n3`, similarily the normal of the plane spanned by `v2, v3` is `n1`, etc?

**Comment by Syntopia** [comment]
This is still very much work-in-progress!

This particular sentence refers to how to construct a point that is lying on two reflection planes, but not on the third - but I will explain this more properly in the final version.

**Comment by neozhaoliang** [comment]
Can one just take the `cross product` of two normals to get a vertor perpendicular to them, instead of usind Gram-Schimdt?

By the way, Todd-Coxeter is the first algorithm that implemented in group theory, but for non-numeric algorithms I guess the searching/sorting algorithms are implemented earlier.

**Comment by Syntopia** [comment]
You could in 3D, but there is no such thing in 4D (Gram-Schmidt is probably the closest thing).

I think my comment about the algorithm was based on this quote: "Later, it was one of the first non-numerical algorithms programmed for electronic computers."

https://ac.els-cdn.com/S0747717108800958/1-s2.0-S0747717108800958-main.pdf?_tid=a984b92b-e2ae-474b-92e1-3d7aba240b9c&acdnat=1522663175_af50e151c10b66b38eeda4e3571081a4

But you are right, Merge sort was implemented in 1945 by Von Neumann on an EDVAC machine - and I'm not even sure that is the first example.

I will update the page to make this clearer.

**Comment by neozhaoliang** [comment]
There is a typo in "Given the generator relations, we know the angles between the reflector planes: If there is a relation on the form: RB^N", missing () here.

**Comment by Syntopia** [comment]
Fixed.

**Comment by neozhaoliang** [comment]
You have explained how to get the initial vertex (then one can get all vertices by acting the quotient group <R,G,B>/<G, B> on it), but how to get the initial edge and a initial face?

**Comment by Syntopia** [comment]
This is what I try to visualize in the 'dodecahedron' demo - you have the large table with all elements (120). Then you create the coset table for e.g. edges by looking at the R,B subgroup (which has four elements, as can also be calculated by Todd-Coxeter). There are 30 'edge' cosets, which tie together vertices. You can now fill in these 30 representative edge cosets, and expand the 30 representants by applying the four R,B group elements.

Similar for faces: the R,G subgroup generates 12 cosets. The R,G subgroup itself has 10 members (I,R,G,GR,RG,RGR,GRG,GRGR,RGRG,RGRGR).

**Comment by neozhaoliang** [comment]
> you have the large table with all elements (120). Then you create the coset table for e.g. edges by looking at the R,B subgroup 

You mean you build the table of all elements in the group `G=<R, G B>` first, then for a subgroup `
H`, build the coset table `G/H` and for each coset `Hx`, hold the list of `g`'s in `Hx`?  This seem a little different from the trafitional relator-based Todd-Coxeter procedure since it builds the coset table `G/H` directly from the relators in G and H.

**Comment by neozhaoliang** [comment]
So the Todd-Coxeter procedure you used here is a little different from the classical one? I mean the classical TC-procedure only assumes  `|G: H|` is finite and works even when `|G|` is infinite. And your code first builds the two tables for `G = <R, G, B>` and `H＝<G, B>`  and then compute the  coset table for `G/H`?

**Comment by neozhaoliang** [comment]
Thanks, I realized that your approach is different from mine. I suggest add the comment that the face-stabilizing subgroup generated by `<R, G>` is the dihedral symmetric group of the face, and one can get all vertices in the face containing `v0` (the initial vertex) by successively applying powers of `RG` to `v0`. For example for the cube `(RG)^4=1`, and a face has `D_8` as its symmetric group, so one can apply `I, RG, (RG)^2, (RG)^3` to `v0` to get the 4 vertices in a face.

**Comment by Syntopia** [comment]
It is an interesting observation that you can just use the powers to get the connectivity. In my implementation, I generate all elements in the subgroup, e.g. for faces in the dodecahedron I generate the 10 elements in the R,G subgroup and apply them. But that leads to double counting. It is quite nice you can just use the powers.

**Comment by neozhaoliang** [comment]
You don't need to compute two tables (one for the total symmetry group and one for <G, B>) to draw the vertices, a single coset table for `<R, G, B> / <G, B>` would suffice. (Of course to draw the edges one needs another table for `<R, G, B> / <R, B>`). It may be a little time-consuming to compute all symmetries when the group is large: for example the symmetry group of the 120-cell contains 14400 elements and even more redundant cosets are defined during the table-filling process, while the vertex/edge/face coset tables are much smaller.

I rendered an image for the 120-cell using this trick with POV-Ray:

![scene](https://user-images.githubusercontent.com/23307174/38852385-483530ac-424c-11e8-800b-ec6779f26e8f.png)

btw, how do you compute the "curved" edge when using stereographic projection to project the 4d edges to the 3d space?

**Comment by Syntopia** [comment]
Looks nice!

I used my JavaScript implementation to calculate the tables shown on the page - the code is available here:
https://syntopia.github.io/Polytopia/toddcoxeter.html  - The 120/600 cell takes ~11 seconds for the full group on my machine. I didn't pursue it any further, because I prefer Knighty's approach.

The curved edges in my 3D->2D illustration were done by simply projecting edge segments to the unit sphere. I imagine that would also work in the 4D case.

The curved edges in the 4D illustration used the ray-marching approach - so they are not drawn directly, Instead, we do the inverse stereographic projection, and map the point back into the fundamental domain, and find the closest edge. One problem here is that faces are somewhat harder. We did find a solution (though I had to ask Knighty for help), but it is computationally heavy: https://plus.google.com/u/0/108188448748343517647/posts/cBHWwE6njRT

**Comment by neozhaoliang** [comment]
I figured out by inserting a list of spheres and using POV-Ray's "sweep_spheres":

![scene](https://user-images.githubusercontent.com/23307174/38981142-401e7120-43f1-11e8-9df7-4255e697547f.png)

Is it easy to draw "soap bubble" faces using shaders and DE trick?

**Comment by neozhaoliang** [comment]
Ok, some of my final results here:
![cube](https://user-images.githubusercontent.com/23307174/39177120-0a5a1aa0-47e1-11e8-8379-3b144e78c5fb.png)
![dodecahedron](https://user-images.githubusercontent.com/23307174/39177133-0da84254-47e1-11e8-99bc-fe9ca5ca863c.png)
![8](https://user-images.githubusercontent.com/23307174/39177143-12809a6a-47e1-11e8-96f8-5288f72b5124.png)
![120](https://user-images.githubusercontent.com/23307174/39177149-14deeab4-47e1-11e8-9be6-b2898713bfca.png)

The 3D polytopes can be unified into the 4D case by viewing their Coxeter diagrams as `p-q-2`.
